version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - env
      - yarn install
  build:
    commands:
      - echo Building and Publishing Project
      - yarn build
      - echo PUBLISHING
      - yarn publish:pypi
  post_build:
    commands:
      - echo I think I would Bump Here!

