version: 0.2

batch:
  fast-fail: true
  build-graph:
    - identifier: release
      buildspec: release.yml
    - identifier: release-pypi
      buildspec: release-pypi.yml
      depend-on:
        - release
    - identifier: release-npm
        buildspec: release-npm.yml
        depend-on:
          - release


