version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - yarn install
  build:
    commands:
      - echo Building and Publishing Project
      - yarn build
  post_build:
    commands:
      - echo I think I would Bump Here!

