version: 0.2

#batch:
#  fast-fail: true
#  build-graph:
#    - identifier: release
#    - identifier: releasePypi
#      buildspec: release-pypi.yml
#      depend-on:
#        - release
#    - identifier: releaseNpm
#      buildspec: release-npm.yml
#      depend-on:
#        - release

phases:
  install:
    commands:
      - echo Installing dependencies
      - env
      - yarn install
      - pip install git-remote-codecommit
  build:
    commands:
      - echo Releasing
      - yarn release
      - git config user.name "Automation"
      - git config user.email "hasanaburayyan21@gmail.com"
      - new_release=$(cat dist/version.txt | xargs -I % echo v%)
      - git tag $new_release main
      - git remote add repo $PROJECT_URL
      - git push repo $new_release
  post_build:
    commands:
      - echo PUBLISH TO PYPI
      - yarn publish:pypi
      - echo PUBLISH TO NPM
      - yarn publish:npm
