version: 0.2

batch:
  fast-fail: true
  build-graph:
    - identifier: release
    - identifier: releasePypi
      buildspec: release-pypi.yml
      depend-on:
        - release
    - identifier: releaseNpm
      buildspec: release-npm.yml
      depend-on:
        - release

phases:
  install:
    commands:
      - echo Installing dependencies
      - env
      - yarn install
  build:
    commands:
      - echo Releasing
      - yarn release
  post_build:
    commands:
      - echo I think I would Bump Here!
